# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 478da10f620e39ba0d222c62d0cfc26ec3aa0a1b1365ece876f80e84ca0af57df61cdd8edf55ff182718eaa3b560f7067f3f6d057b2fd6cdf2bea067efb37bba

test:
  secret_key_base: fef113066411e8b024f1988805b71e6555257f1694d17da7001525397eed69323d9dc8193c69fa1e7d72b7c97a7aeaff4e560d3b882a6da3fb48c53dc0b992b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
